version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: turbo-npn-postgres
    restart: always
    environment:
      POSTGRES_USER: npn
      POSTGRES_PASSWORD: turbo
      POSTGRES_DB: turbodb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
